version: '3.8'

services:
  web:
    container_name: cdnsave
    image: "docker.pkg.github.com/dschek/cdnsave/cdnsave:latest"
    ports:
      - "9302:8080"
    environment:
      - port=$port
      - host=$host
      - login=$login
      - password=$password
      - imgUrl=$imgUrl