version: '3.8'

services:
  web:
    container_name: cdnsave
    image: "docker.pkg.github.com/dschek/cdnsave/cdnsave:latest"
    ports:
      - "9302:8080"
    environment:
      - sftpport=$sftpport
      - sftphost=$sftphost
      - sftplogin=$sftplogin
      - sftppassword=$sftppassword
      - imgurl=$imgurl