sftp:
  port: ${port:21}
  host: ${host:cdn.tydi.net}
  login: ${login:user123}
  password: ${password:12345678}
app:
  host:
    img: ${imgUrl:https://img.tydi.ru/}
server:
  port: ${PORT:8080}
  tomcat:
    uri-encoding: UTF-8