sftp:
  port: ${sftpport:21}
  host: ${sftphost:cdn.tydi.net}
  login: ${sftplogin:user123}
  password: ${sftppassword:12345678}
app:
  host:
    img: ${imgurl:https://img.tydi.ru/}
server:
  port: ${PORT:8080}
  tomcat:
    uri-encoding: UTF-8