name: Java CI with Gradle

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: set global env
        id: pr
        run: echo "::set-output name=NAME::cdnsave"
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: gradle
      - name: Add Gradle Wrapper for strating Gradlew
        run: gradle wrapper
      - name: Build with Gradle
        run: ./gradlew build
      - name: set global env
        id: global_env
        run: echo "::set-output name=DOCKERHUB_IMAGE_NAME::docker.pkg.github.com/dschek/${{ steps.pr.outputs.NAME}}/${{ steps.pr.outputs.NAME}}"
      - name: Build and tag image
        run: docker build -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:latest" -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:${GITHUB_SHA::8}" .
      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}
      - name: Publish image
        run: docker push "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}"
